version: "3"
services:
  nginx:
    ports:
      - "8080:80"
  gateway:
    build:
      context: ./gateway
      args:
        NODE_ENV: development
    env_file:
      - ./gateway/.env
    command: npm run dev
  account-bck:
    build:
      context: ./account
      args:
        NODE_ENV: development
    env_file:
      - ./account/.env
    command: npm run dev
